config/routes.rb
Rails.application.routes.draw do

  root 'public/home#top'

  devise_for :members, controllers:{
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_for :admins, controllers:{
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :public do
    get 'about' => 'home#about'
    get 'confirm' => 'members#confirm'
    put 'confirm' => 'members#hide'
    get 'mypage' => 'members#show'
    get 'mypage/edit' => 'members#edit'
    patch 'mypage' => 'members#update'
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
  	resources :orders, only: [:new, :index, :show, :create]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show, :create] do
      get 'search', on: :collection
    end
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    get 'top' => 'home#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def cart_item_sum
    total = 0
    cart_items.each do |cart_item|
      total += cart_item.subtotal_price
    end
    total
  end

  # カート商品合計個数
  def cart_total_count
    quantity = 0
    cart_items.each do |cart_item|
      quantity += cart_item.quantity
    end
    quantity
  end

  #退会ステータス０＝有効のみログイン可
  def active_for_authentication?
    super && (self.leave_status == 0)
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
	before_action :authenticate_admin!
	
	def index
	  @members = Member.page(params[:page])
		# 検索オブジェクト
    @search = Member.ransack(params[:q])
    # 検索結果
    @q_members = @search.result.page(params[:page])
	end

	def show
		@member = Member.find(params[:id])
	end

	def edit
		@member = Member.find(params[:id])
	end

	def update
		@member = Member.find(params[:id])
		if @member.update(member_params)
			redirect_to admin_member_path(@member), notice:'アカウント情報を更新しました'
		else
			render 'edit'
		end
    end

	private
    def member_params
      params.require(:member).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_number, :email, :leave_status)
    end

end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/_member_list.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% members.each do |member| %>
    <tr>
      <td><%= member.id %></td>
        <td><%= link_to member.last_name+member.first_name, admin_member_path(member.id) %></td>
        <td><%= member.email %></td>
        <td>
          <% if member.leave_status == 1 %>
          <p>退会済み</p>
          <% else %>
          <p>有効</p>
          <% end %>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/members/_search.html.erb
<%= search_form_for [:admin, search] do |f| %>
  <div class="member_search_form">
    <div class="form-group row">
      <div class="col-xs-12">
        <%= f.label :last_name_cont, :会員を検索する %><br>
        <%= f.search_field :last_name_cont, placeholder: "例)田中", autofocus: true, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-xs-12">
        <%= f.label :leave_status_eq, :退会ステータス %><br>
        <%= f.select :leave_status_eq, [["有効", 0], ["退会済み", 1]], include_blank: "--選択してください--", autofocus: true, class: "form-control" %>
      </div>
    </div>
    <div class="item_search_btns">
      <%= f.submit "検索", class:"btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/admin/members/edit.html.erb
<h3><%= @member.last_name %><%= @member.first_name %>の会員情報編集</h3>

<%= form_for(@member, url: admin_member_path) do |f| %>

  <div class="form-group">
    <%= f.label :顧客ID, class: "col-xs-2 control-label" %>
    <%= @member.id %>
  </div>

  <div class="form-group">
    <%= f.label :氏名, class: "col-xs-2 control-label" %>
    <%= f.text_field :last_name, autofocus: true %>
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :フリガナ, class: "col-xs-2 control-label" %>
    <%= f.text_field :kana_last_name, autofocus: true %>
    <%= f.text_field :kana_first_name, autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :郵便番号, class: "col-xs-2 control-label" %>
    <%= f.text_field :postal_code, autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :住所, class: "col-xs-2 control-label" %>
    <%= f.text_field :address, autofocus: true, collection: JpPrefecture::Prefecture.all, :value_method => :name, class: "size-input" %>
  </div>

  <div class="form-group">
    <%= f.label :電話番号, class: "col-xs-2 control-label" %>
    <%= f.text_field :phone_number, autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :メールアドレス, class: "col-xs-2 control-label" %>
    <%= f.email_field :email, autofocus: true, class: "size-input" %>
  </div>

  <!-- ステータス：1 = 退会済み 0 = 有効 -->
  <div class="form-group">
    <%= f.label :会員ステータス, class: "col-xs-2 control-label" %>
    <%= f.radio_button :leave_status, 0 %>
    <%= f.label :leave_status, "有効", {value: :leave_status, style: "display: inline-block;"} %>
    <%= f.radio_button :leave_status, 1 %>
    <%= f.label :leave_status, "退会済み", {value: :leave_status, style: "display: inline-block;"} %>
  </div>

  <div class="actions row">
      <%= f.submit '変更を保存する',　class:"data-disable-with", class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/members/index.html.erb
<div class="col-sm-3">
  <h3>詳細検索</h3>
  <h4><%= link_to "全会員を表示", admin_members_path %></h4>
  <%= render 'search', search: @search %>
</div>

<% if @q_members %>
  <%# 検索該当なしの場合 %>
  <% if @q_members.empty? %>
    <div class="col-sm-9">
      <h3>会員一覧</h3>
      <p class="top-empty-message">条件に合う会員が見つかりませんでした</p>
    </div>
  <% else %>
    <%# 検索該当ありの場合 %>
    <div class="col-sm-9">
      <h3>会員一覧</h3>
      <p><%="全#{@q_members.total_count}件中" + "(#{@q_members.count}件表示)" %></p>
      <%= render 'member_list', members: @q_members %>
      <div class="row text-center">
        <%= paginate @q_members, class: "paginate" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/members/show.html.erb
<h3><%= @member.last_name %><%= @member.first_name %>の会員詳細</h3>

<table class='table'>
	<tr>
		<th>顧客ID</th>
		<th><%= @member.id %><% if @member.leave_status == 1 %>
			<p>退会済み</p>
          <% else %>
          <p>有効会員</p>
          <% end %></th>
	<tr>
		<th>氏名</th>
		<th><%= @member.last_name %><%= @member.first_name %></th>
	</tr>
	<tr>
		<th>フリガナ</th>
		<th><%= @member.kana_last_name %><%= @member.kana_first_name %></th>
	</tr>
	<tr>
		<th>郵便番号</th>
		<th><%= @member.postal_code %></th>
	</tr>
	<tr>
		<th>住所</th>
		<th><%= @member.address %></th>
	</tr>
	<tr>
		<th>電話番号</th>
		<th><%= @member.phone_number %></th>
	</tr>
	<tr>
		<th>メールアドレス</th>
		<th><%= @member.email %></th>
	</tr>
</table>

<%= link_to '編集する', edit_admin_member_path(@member), class:"btn btn-default col-xs-6" %>
<%= link_to '注文履歴一覧を見る', admin_orders_path(order: 'member'),class:"btn btn-default col-xs-6" %>