config/routes.rb
Rails.application.routes.draw do

  root 'public/home#top'

  devise_for :members, controllers:{
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_for :admins, controllers:{
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :public do
    get 'about' => 'home#about'
    get 'confirm' => 'members#confirm'
    put 'confirm' => 'members#hide'
    get 'mypage' => 'members#show'
    get 'mypage/edit' => 'members#edit'
    patch 'mypage' => 'members#update'
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
  	resources :orders, only: [:new, :index, :show, :create]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show, :create] do
      get 'search', on: :collection
    end
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    get 'top' => 'home#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :member
	has_many :order_items, dependent: :destroy

	validates :pay_type, presence: true
	validates :postal_code, presence: true, length: { minimum: 7, maximum: 7 }
	validates :address, presence: true
	validates :delivery_name, presence: true

	attr_accessor :registered_address, :delivery_info
	DELIVERY_INFO_DEFAULT = "self_addr"
	after_initialize do |obj|
		obj.delivery_info ||= DELIVERY_INFO_DEFAULT
	end

	enum pay_type: { credit: 0, bank: 1 }
	enum delivery_info: { self_addr: 0, registered_addr: 1, new_addr: 2 }
	enum order_status: { pending: 0, confirmed: 1, making: 2, preparing: 3, delivered: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :authenticate_admin!
	
	# today,member,allで分岐して表示内容を変更
	def index
		case params[:order]
		# 本日の注文一覧（admin/topから）
		when 'today'
			@orders = Order.page(params[:page]).reverse_order.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
		#会員の注文履歴一覧（会員のマイページから)
		when 'member'
			member_id = Rails.application.routes.recognize_path(request.referer)[:id]
			@member = Member.find(member_id)
			@orders = @member.orders.page(params[:page]).reverse_order
		#admin/注文履歴一覧（ヘッダーから）
		when 'all'
		    @orders = Order.page(params[:page]).reverse_order
		    # 検索オブジェクト
			@search = Order.ransack(params[:q])
			# 検索結果
			@q_orders = @search.result.page(params[:page]).reverse_order
		end
	end


	def show
		@order = Order.find(params[:id])
		case @order.pay_type
			when "credit" then
				@pay = "クレジットカード"
			when "bank" then
				@pay = "銀行振込"
			end
	end

	def update
		@order = Order.find(params[:id])
		order_items = @order.order_items.all
		if @order.update(order_params)
			# 注文状況が１＝入金確認になったら、製作待ち１に
			if @order.order_status == "confirmed"
				order_items.each do |order_item|
					order_item.update(product_status: 1)
				end
			end
			redirect_to admin_order_path(@order.id), notice:'ステータスを更新しました'
		end
	end

	private
    def order_params
      params.require(:order).permit(:total_fee, :postage, :pay_type, :postal_code, :address, :delivery_name, :order_status, :product_status)
    end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_order_list.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% orders.each do |order| %>
    <tr>
      <td><%= link_to order.created_at.strftime('%Y/%m/%d/  %H:%M'), admin_order_path(order.id) %></td>
        <td><%= order.member.last_name%><%= order.member.first_name%></td>
        <td><%= order.order_items.sum(:quantity) %></td>
        <td>
          <%= order.order_status_i18n %>
        </td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/orders/_search.html.erb
<%= search_form_for @search, url: admin_orders_path do |f| %>
  <div class="form-group row">
    <div class="col-xs-12">
      <%= f.label :order_status_eq, :注文ステータス %><br>
      <%= f.select :order_status_eq, Order.order_statuses.map{|k, v| [Order.order_statuses_i18n[k], v]}, include_blank: "--選択してください--" %>
      <%= hidden_field_tag :order, 'all' %>
    </div>
  </div>
  <div class="order_search_btns">
    <%= f.submit "検索", class:"btn btn-info" %>
  </div>
<% end %>

app/views/admin/orders/index.html.erb
<% if @q_orders %>
  <div class="col-sm-3">
    <h3>詳細検索</h3>
    <h4><%= link_to "全注文履歴を表示", admin_orders_path(order: 'all') %></h4>
    <%= render 'search', search: @search %>
  </div>
  <%# 検索該当なしの場合 %>
  <div class="order-content">
    <% if @q_orders.empty? %>
      <div class="col-sm-9">
        <h3>注文履歴一覧</h3>
        <p class="top-empty-message">条件に合う注文が見つかりませんでした</p>
      </div>
    <% else %>
      <%# 検索該当ありの場合 %>
      <div class="col-sm-9">
        <h3>注文履歴一覧</h3>
        <p><%="全#{@q_orders.total_count}件中" + "(#{@q_orders.count}件表示)" %></p>
        <%= render 'order_list', orders: @q_orders %>
        <div class="row text-center">
          <%= paginate @q_orders, class: "paginate" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="col-sm-3">
    <h3>詳細検索</h3>
    <h4><%= link_to "全注文履歴を表示", admin_orders_path(order: 'all') %></h4>
  </div>
  <%# 検索機能なしの場合 %>
  <div class="col-sm-9">
    <h3>注文履歴一覧</h3>
    <p><%="本日の注文 #{@orders.total_count}件を表示" %></p>
    <%= render 'order_list', orders: @orders %>
    <div class="row text-center">
      <%= paginate @orders, class: "paginate" %>
    </div>
  </div>
<% end %>

app/views/admin/orders/show.html.erb
<h3>注文履歴詳細</h3>

<p>購入者  <%= @order.member.last_name %><%= @order.member.first_name %></p>
<p>配送先　<%= @order.address %><br>
	      <%= @order.delivery_name %></p>
<p>支払方法　<%= @pay %></p>
<p>注文ステータス<%= form_for [:admin, @order] do |f| %>
  <%= f.select :order_status, Order.order_statuses_i18n.keys.map { |k| [Order.order_statuses_i18n[k], k]} %>
  <%= f.submit '更新', class: "btn btn-success " %>
  <% end %>
</p>

<table class='table'>
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order.order_items.each do |order_item| %>
    <tr>
        <td><%= order_item.item.name %></td>
        <td>¥ <%= (order_item.item.price * 1.1).floor %></td>
        <td><%= order_item.quantity %></td>
        <td>¥ <%= (order_item.quantity * order_item.item.price * 1.1).floor %></td>
        <td>
            <%= form_with model: order_item, url: admin_order_item_path(order_item.id), local: true do |f| %>
            <%= f.select :product_status, OrderItem.product_statuses.keys.map { |k| [OrderItem.product_statuses_i18n[k], k]} %>
            <%= f.submit '更新', class: "btn btn-success " %>
            <% end %>
        </td>
    </tr>
    <% end %>

  </tbody>
</table>