config/routes.rb
Rails.application.routes.draw do

  root 'public/home#top'

  devise_for :members, controllers:{
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_for :admins, controllers:{
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :public do
    get 'about' => 'home#about'
    get 'confirm' => 'members#confirm'
    put 'confirm' => 'members#hide'
    get 'mypage' => 'members#show'
    get 'mypage/edit' => 'members#edit'
    patch 'mypage' => 'members#update'
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
  	resources :orders, only: [:new, :index, :show, :create]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :items, only: [:index, :show, :create] do
      get 'search', on: :collection
    end
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    get 'top' => 'home#top'
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :member
	belongs_to :item

	validates :quantity, presence: true

	def subtotal_price
		(quantity * item.price * 1.1).floor
	end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :member
	validates :postal_code, presence: true, length: { minimum: 7,maximum: 7 }
	validates :address, presence: true
	validates :name, presence: true

	def collect_delivery
		self.postal_code + self.address + self.name	
	end
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items

	validates :genre, presence: true
	validates :invalid_status, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :order_items, dependent: :destroy
	belongs_to :genre
	has_many :cart_items, dependent: :destroy
	attachment :image

	validates :name, presence: true
	validates :introduction, presence: true
	validates :price, presence: true
	validates :sale_status, presence: true

	def price_with_tax
		(price * 1.1).floor
	end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def cart_item_sum
    total = 0
    cart_items.each do |cart_item|
      total += cart_item.subtotal_price
    end
    total
  end

  # カート商品合計個数
  def cart_total_count
    quantity = 0
    cart_items.each do |cart_item|
      quantity += cart_item.quantity
    end
    quantity
  end

  #退会ステータス０＝有効のみログイン可
  def active_for_authentication?
    super && (self.leave_status == 0)
  end

end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :member
	has_many :order_items, dependent: :destroy

	validates :pay_type, presence: true
	validates :postal_code, presence: true, length: { minimum: 7, maximum: 7 }
	validates :address, presence: true
	validates :delivery_name, presence: true

	attr_accessor :registered_address, :delivery_info
	DELIVERY_INFO_DEFAULT = "self_addr"
	after_initialize do |obj|
		obj.delivery_info ||= DELIVERY_INFO_DEFAULT
	end

	enum pay_type: { credit: 0, bank: 1 }
	enum delivery_info: { self_addr: 0, registered_addr: 1, new_addr: 2 }
	enum order_status: { pending: 0, confirmed: 1, making: 2, preparing: 3, delivered: 4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
	enum product_status: { ng: 0, waiting: 1, making: 2, done: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@genre = Genre.new
		@genres = Genre.page(params[:page])
	end

	def create
		@genre = Genre.new(genre_params)
		if @genre.save
			flash[:notice] = "ジャンルを追加しました"
			redirect_to admin_genres_path
		else
			@genres = Genre.page(params[:page])
			render action: :index
		end
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
		items = @genre.items.page(params[:page])
		if @genre.update(genre_params)
			flash[:notice] = "ジャンル情報を編集しました"
			redirect_to admin_genres_path
		else
			render action: :edit
		end
  end

	private
		def genre_params
			params.require(:genre).permit(:genre, :invalid_status)
		end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :authenticate_admin!

  def top
    @count = Order.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_action :authenticate_admin!

	def index
		@items = Item.page(params[:page])

		# 検索オブジェクト
		@search = Item.ransack(params[:q])
    # 検索結果
			@q_items = @search.result.page(params[:page])
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end

	def create
			@item = Item.new(item_params)
			if @item.save
					redirect_to admin_item_path(@item.id), notice:'商品を作成しました'
			else
					render 'new'
			end
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
				redirect_to admin_item_path(@item.id), notice:'商品情報を更新しました'
		else
			render 'edit'
		end
	end

	private
	def item_params
		params.require(:item).permit(:name, :introduction, :genre_id, :price, :image, :sale_status)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		# 管理者ログイン後　＝＞　トップページ
		if admin_signed_in?
			admin_top_path
		# 会員ログイン後　＝＞　トップページ
		elsif member_signed_in?
			root_path
		end
  end

  #sign out後トップページへ
  def after_sign_out_path_for(resource)
  	# 会員ログアウト後　＝＞　トップ画面
  	if resource == :member
  		root_path
  	# 管理者ログアウト後　＝＞　ログイン画面
  	elsif resource == :admin
  		admin_session_path
  	end
  end

  def set_search_item
    # 検索バー表示の @q
    @q = Item.ransack(params[:q])
  end

  protected
	def configure_permitted_parameters
		#signup/ユーザー登録情報
		devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_number, :email, :leave_status])
		#login：name要
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>
  </head>

  <body>
    <div class="wrapper">
      <!-- Header -->
      <header>
        <div class="container">
            <%= link_to(root_path, class:"header-logo") do %>

            <nav class="nav navbar-nav navbar-left">
                <%= image_tag 'Apple.jpg' %>
            </nav>
            <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if admin_signed_in? %>
              <li><%= link_to '商品一覧', admin_items_path %></li>
              <li><%= link_to '会員一覧', admin_members_path %></li>
              <li><%= link_to '注文履歴一覧', admin_orders_path(order: 'all') %></li>
              <li><%= link_to 'ジャンル一覧', admin_genres_path %></li>
              <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
              <li><i class="fab fa-instagram fa-2x icon"></i></li>

            <% elsif member_signed_in? %>
              <li>ようこそ、<%= current_member.last_name %> <%= current_member.first_name %>さん！</li>
              <li><%= link_to 'マイページ', public_mypage_path(current_member), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to '商品一覧', public_items_path, class: 'glyphicon glyphicon-share-alt' %></li>
              <li><%= link_to "カート(#{current_member.cart_items.count})", public_cart_items_path, class: 'glyphicon glyphicon-shopping-cart' %></li>
              <li><%= link_to 'ログアウト', destroy_member_session_path, method: :delete, class: 'glyphicon glyphicon-log-in' %></li>
              <li><i class="fab fa-instagram fa-2x icon"></i></li>

            <% else %>
            　<li><%= link_to 'About', public_about_path %></li>
              <li><%= link_to '商品一覧', public_items_path %></li>
              <li><%= link_to '新規登録', new_member_registration_path %></li>
              <li><%= link_to 'ログイン', new_member_session_path %></li>
              <li><i class="fab fa-instagram fa-2x icon"></i></li>
            <% end %>
          </ul>
        </div>
      </header>

      <!-- Main -->
      <div class='body'>
        <div class='container'>

          <p id="notice"><%= notice %></p>

          <%= yield %>
        </div>
      </div>

      <!-- Footer -->
      <footer class="footer">
        <% if admin_signed_in? %>
          <%= link_to admin_top_path do %>
          <div class="container text-center mt-3">
            <p>©NaganoCake by 焼きApple</p>
          </div>
          <% end %>
        <% elsif member_signed_in? %>
          <div class="container text-center mt-3">
            <p>©NaganoCake by 焼きApple</p>
          </div>
        <% else %>
          <%= link_to new_admin_session_path do %>
          <div class="container text-center mt-3">
            <p>©NaganoCake by 焼きApple</p>
          </div>
          <% end %>
        <% end %>
      </footer>

    </div>
  </body>
</html>